version: '3.8'

services:
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - default

volumes:
  database_data:


networks:
  default:
    name: ${NETWORK_NAME}