version: '3.8'

services:
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - cidadao_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    ports:
      - 5173:5173
    depends_on:
      - php
    networks:
      - cidadao_network

  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - database
    networks:
      - cidadao_network

volumes:
  database_data:


networks:
  cidadao_network:
    name: ${NETWORK_NAME}