nelmio_api_doc:
    documentation:
        info:
            title: Documentação da API
            description: Documentação da API para o teste da Vaga de Desenvolvedor Back-end
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
